### ISSUE TITLE
Strange output from script

### ISSUE THREAD

**Issue by vladkorotnev** [denandz/lpc_sniffer_tpm#1]
Hello, I am trying to attempt the same experiment of dumping the keys from a TPM but cannot find any similar values in the output stream.

There are also weird spots like this in the output:

```
b'00000024c400'
b'000000240000'
b'000000240000'
b'000000240000'
b'00000024'
b'00'
b'000000240000'
b'000000240000'
b'000000240000'
b'000000240000'
```

As if a part of data just "fell out" for some reason.

What might this designate? I am new to FPGA and couldn't find what the reason might be on the python side.

Many thanks in advance.

**Comment by denandz** [comment]
Hiya, do you have the complete log for the system boot with the sniffer attached that you can share? Also did you notice the overflow LED flashing at all? Did you enable the Icestick's second serial interface is for fast-opto mode?

**Comment by vladkorotnev** [comment]
Fast-opto is enabled indeed, no overflows but the red (not green) led is constantly illuminated even when there is no data.

I have taken 6 captures and put them here https://gist.github.com/vladkorotnev/5d68a9f49f600598800a4d887f0f05f7

The LCLK line on the LPC test pads on my mainboard doesn't have continuity with the TPM though (everything else does), but I assume this is because the clock line is routed through some sorts of amplifier?

I also suspected wiring length but then again the wires in the original article are even about twice longer than mine.

**Comment by denandz** [comment]
The CLK being inconsistent with the TPM would cause issues, can you try taking the clock signal from the TPM chip directly?

**Comment by vladkorotnev** [comment]
Sounds like an idea but it's gotta be hard (it's the same Infinion as in your first experiment). I might try todays evening. Why would CLK be different on the chip and on the header labeled explicitly as LPC1 though? Also, if there is a data byte on the bus which is equivalent to a newline character, wouldn't that cause the same looking logs?

I wonder however why the beginning of the logs is inconsistent in some ways too though.

**Comment by denandz** [comment]
The inconsistent data sounds like CLK weirdness to me, not sure why it would be different on the chip versus the header though. Parse.py is using readline(), which is kind of silly, so I think you're right, an `0x0A` on the bus could cause the odd logs for sure, but that wouldn't explain why you're not seeing the VMK data?

**Comment by denandz** [comment]
You can try something like:

```
while True:
    print(hexlify(ser.read())
```
Unfortunately my test rig has been torn down, so I can't test right now :(

**Comment by vladkorotnev** [comment]
I would also split the loop to read whole frames (8 bytes or what it was?) to avoid turning it into a mess of data. 

But yeah the CLK is suspicious too. I'm gonna buy some proper flux and redo the soldering just in case.

**Comment by vladkorotnev** [comment]
Come to think of it, I see such loose '02's in your screencast in the article too, so that seems common. 

May it be that BitLocker is not storing a VMK in the TPM in my case? This system has 2 drives, with multiple partitions. Despite reading that usually it stores the C drive keys in the TPM and the further auto unlocked drives keys in the registry, who knows. I've not used Windows much after Win2000...

Should the data be the same on every single startup, though? Because if that's the case then it proves the capture is not going correctly.

**Comment by denandz** [comment]
Try using something like bdeinfo from a live linux distro, it should tell you what protectors are in use. Looking at your log, if I look for TPM `TPM_TAG_RQU_COMMAND` writes (`00c1`) I can see the PCR extends (command `00000014`) and stuff but then everything stops making sense (apologies in advanced for my hacky regex, there's a couple overlaps in the output but you get the idea)

```
doi@buzdovan:~$ cut -f 2 -d\' log1  | grep '24..02$' | perl -pe 's/.{8}(..)..\n/$1/' | perl -pe 's/(00c[1234])(.{8})(.{8})/\n$1 $2 $3 /g' ;echo

00c1 0000000c 00000099 0001
00c1 00000000 00005300 c10000002200000014000000
00c4 2fedad26 8200cb1d 15f97841c344e79dae3320
00c1 00000016 00000065 000000040000000400000108
00c1 0000000c 40000000 20
00c1 0000000c 40000000 04
00c1 00000022 00000014 000000004c6d6c717e87da93323877a8d95f4b63e433643a
00c1 00000016 00000065 000000040000000400000108
00c1 00000016 000000cf 5001000000000000000000
00c1 00000022 00000014 00000002858ea8da3cb13babdfeeb2a928759cbdd2e2c25a
00c1 00000022 00000014 000000022c9e70f882c56a1488f1f1b748418a10e85439
00c1 00000022 00000014 00000002ad270917993c0fdcaf3a8971c222f1b3b96f0672
00c1 00000022 00000014 000000029b7b1affbe1e59f966479a7f30fa6f5d6dce53ab
00c1 00000022 00000014 00000002f6059dad2af809afce67618dc34dff8476996704
00c1 00000016 000000cf 5001000000000000000000
00c1 00000016 00000065 000000040000000400000108
00c1 00000016 00000065 0000000500000400000111
00c1 00000022 00000014 0000000244f71b8be8800dff62bc463ca40f004fbd108a
00c1 00000022 00000014 00000002f42a40670cf27a54713f28cc004928f51f8644f6
00c1 00000022 00000014 00000002607ae846027f80978a611b5eab512d9a42290cd8
00c1 00000022 00000014 00000002868a1e48243629c8ba950faac0fd2f898d4405d5
00c1 00000022 00000014 00000002af68579405ba742bd6d7024762b50208f5dd1ee3
00c1 00000022 00000014 000000009d2d0b8a6b088e3e4c7cdf499c220f4d51c55fb4
00c1 00000022 00000014 00000001ce050bf96796d50ba8f5f4b98feb82c801781a
00c1 00000022 00000014 00000000d9be6524a5f5047db5866813acf3277892a7a3
00c1 00000022 00000014 00000001d9be6524a5f504b5866813acf3277892a7a3
00c1 00000022 00000014 00000002d9be6524a5f5047db5866813acf3277892a7a3
00c1 00000022 00000014 00000003d9be6524a5f5047db5866813acf3277892a7a3
00c1 00000022 00000014 00000004d9be6524a5f5047db5866813acf3277892a7a3
00c1 00000022 00000014 00000005d9be6524a5f5047db5866813acf3277892a7a3
00c1 00000022 00000014 00000006d9be6524a5f5047db5866813acf3277892a7a3
00c1 00000022 00000014 00000007d9be6524a5f5047db5866813acf3277892a7a3000000005c3f6b0dc78d57296aa2870ca6f782ccf80f00000000967fcf2bfee1e3b2971de540115048c800000000adca34ee2bb8b2f2170cd34f00000000a3b4f7dd6a53b45a3ca8fb7900000000843a3baad0f54bdffd92a3b962e00767f6d900000000a1e6cc93b050f4698aa759f44f4faa502006000000005355968120efb68d844cda3c8e4f50f3a7ed000000005553b0ecc55f90500183bf5c2628fcee70d100000000000400000014000000000b00000000000400000006000000c898000000000000c82e1c010000000000000000000000000000000000000000806a2f75dd6d930d745c380ccc86b2a1350f603800000000000000010000000000000036000601010003150f000003150f00d63d60dcac75349983c5666c69dc6dca12368397bdbf77e06a8cd32436c4e4c8c8ea9e082953e16b0000010026579c09a62acb18252ebd22cd00ce88108268063880a37773e491a179bcd4a3d1468e422abd3043beaf71b849105233dc8ed1ff566ef11d7e17495c2fbab5597d3f161470d61213ff55ff20c1d026707ca74405bd3e91af584146e3765940ca6e14b9d2ffd92cd8ceb47455153525c35ff9d4ba624bf49a23d6c3971b87dc6cb2c08a7e7a5472ea48873b453effa210ee0b42c9812806b9ba882ec5d77c6292ff2ccc68323a6d22c7b0188876f1c5b1c59d652b03158d850d4728f807b1ede28ba576112061b776109ab72eebbaee81f812c7b3a97849fc8f378724bfc812ffbf91876ff6f9952f9f68fcdaaade5580dd6d60c69436edc1e815e0a5665d006abec901000000000000000000000000000000000000000054a28a61ba0dcc2a3786805ca7f37214c1704900957479010000000000000000000000000000000000000000552b43b14e89b250376cac19b48529a515e958aa000000000b00000000ca78e745285173431b3e52c5c25299e473000000003d4804a127d9ea492618744722ff29b05f0400000000576c5dcfbed5bbed7ff654c2b7b8aad30000000060a7193434b25ee8870827fd436b125aa03d00000000000400000014000000000b00000000140000000014000000006060af3003d238948847dcf405ae8b2aaa7700000000bd8608dc8f43c3a49c8804c1f90d1dc054
```

The unseal command should look like `00c3 <length> 00000018 ........`.

Something funky is going on for sure. If you know that CLK is suspect, I'd start there.

**Comment by denandz** [comment]
TPM1.2 values and stuff are here https://github.com/tianocore/edk2/blob/7367cc6c24d01b400d2370ffd58ae02854a56b32/MdePkg/Include/IndustryStandard/Tpm12.h if you need them. I usually reference the TPM Part 3 - Commands document for the structure of the TPM message then look it up in Tpm12.h to find the hex value or whatever.

**Comment by vladkorotnev** [comment]
What do you mean by "stops making sense"? Is there some common sequence of commands to look out for? And should the sequence/data be persistent across reboots?

**Comment by denandz** [comment]
The data doesn't look like TPM commands any more. Take a look at https://trustedcomputinggroup.org/wp-content/uploads/TPM-Main-Part-3-Commands_v1.2_rev116_01032011.pdf for what the data structure is meant to be. 

The data should be similar across boots, but I can't say for certain if it'll be exactly the same. You should see the same TPM commands coming through though. Init, pcrextend, getcapabilities, unseal, etc

**Comment by denandz** [comment]
If you have a logic analyzer or a scope handy, can you see if there is any difference between CLK on the TPM chip and on your debug header?

**Comment by vladkorotnev** [comment]
Sadly, neither. 
The only way I guess is to solder directly to the chip for the CLK line.

On a sidenote, even though extremely unlikely to be that, would something similar like in my logs be produced if I mistakenly swapped the CLK/FRAME lines? (Contrary to the article, I probably can trust my tools now, myself though -- not so much, huh)

**Comment by denandz** [comment]
If you swapped CLK and FRAME lines I would expect that you wouldn't see anything at all! I can see valid TPM commands in the log, if the wiring was incorrect I'd think that there would be no data that looks like valid TPM command data structures. Either way, it couldn't hurt to double check all the wiring and make sure everything is plugged together correctly.

**Comment by vladkorotnev** [comment]
All this reminds me how once I was building a ZX Spectrum keyboard converter and some PS/2 events came through fine but others not, depending on the 2 LSB in the character, if they were the same, it went through fine, if they were different (01 or 10), welp, depends on how lucky you are you get a 00 or 11. So wiring is better to be re-checked for sure.

Can the capacitance of the data wires or the surrounding electrical noise affect the readout? If so, would swapping the wires to an IDE ribbon cable with ground wires in-between the signal wires help? 

Then again that would add capacitive coupling to ground and probably more than the current mess-o'-loose-wires does...

**Comment by vladkorotnev** [comment]
I also just checked and my TPM is the same infineon but 2.0, might that affect anything?

**Comment by vladkorotnev** [comment]
Connecting the CLK line directly to the chip seems to make no difference, I'll try to shorten the wires as the next measure


Update: no difference as well. I've thoroughly checked all the connections so that the A0..3 lines are not messed up. No dice, everything is connected spot on. May there be a case when data is lost but the LED does not light up?

**Comment by denandz** [comment]
Yea, it could potentially be overflowing the buffer intermittently if there is a huge amount of TPM traffic. You can try commenting out lines 127 and 128 in `lpc.v`, which will stop it from sniffing TPM writes, so you should only get data read back from the TPM. That'll reduce the amount of data being written to the ring buffer.

**Comment by vladkorotnev** [comment]
Them being 

```
                                                if (addr == 32'h24)
                                                    out_clock_enable <= 1;
```

is that right?

I'm thinking maybe something stupid like baud rates... Does OPTO need to be enabled AFTER programming the icestick, or is it okay to enable it BEFORE (as I did)?

**Comment by denandz** [comment]
Yup, comment those out. I enabled fast opto on mine before programming anything and it all worked out fine, the FTDI chip config wont be messed with by programming the FPGA.

**Comment by vladkorotnev** [comment]
Just to make sure, those lines do what? I'm new to FPGA so it doesn't seem to me they write anything anywhere, or do they raise some kind of an "enable" pin which lets the output clock through?
I'll double check OPTO because I've been programming it in Windows and it's a good idea to double check anything related to Windows...

Also this line `parameter CLOCK_FREQ = 33_000_000`: would raising it increase the sample rate thus enable better capture? In case the bus frequency is higher on this mainboard I'm investigating.

**Comment by vladkorotnev** [comment]
I commented out the lines and now I get no output at all

**Comment by denandz** [comment]
Not sure what to tell you, with those lines commented out you should be logging TPM read messages. I've had my setup in that configuration running on both TPM 1.2 and TPM 2.0 chips successfully. 

I'd suggest purposefully stepping through the process from start to finish. Flash the FPGA, unplug it from your usb port, make sure your main board is powered off, plug in the FPGA, run parse.py and then boot the main board. Aside from that, without physically being in front of your device I can't really offer much more help.

**Comment by vladkorotnev** [comment]
Another thing is the fpga code specifies 33 MHz while the bus is apparently 33.3 -- may that make a difference?

I've been also worried a part of the FPGA may be damaged (ESD or something), so I swapped out the pin definitions to the other side of the Icestick. While this seems to produce more of a consistent result, doesn't seem to help much as there is still no key or unseal message (not even "c3" in any logs at all).

Something tells me the LPC breakout on the mainboard is somewhat trickier than it seems to be.

**Comment by vladkorotnev** [comment]
Looking at the datasheet it specifies address 2E and 2F, or 4E and 4F -- where did the magic 00000024 even come from? 

Using the original project I can see lots of reads from 2f and writes to 2e, 24h doesn't even grep out...

**Comment by denandz** [comment]
I suggest reading https://trustedcomputinggroup.org/wp-content/uploads/PC-Client-Specific-Platform-TPM-Profile-for-TPM-2-0-v1-03-22-170516_final.pdf and the original article. I haven't experienced your issues, and there is nothing further I can offer. Closing this issue.

**Comment by vladkorotnev** [comment]
Many thanks for your help!
