### ISSUE TITLE
Issues sniffing TPM1.2

### ISSUE THREAD

**Issue by Istvan-at** [denandz/lpc_sniffer_tpm#3]
Hi,

Thank you for writing such a great article!
I tried  your algorythm on several test devices.
With one it worked like a charm, so I´m quite sure that I´ve got the FPGA settings right.
When I started trying it on another device, I was kinda puzzled - I did not get any read instructions, only write ones and the particular value 0b000000242010 repeated multiple times.
I attached two log files as an example. 

Any idea what I might be doing wrong?
[log1.txt](https://github.com/denandz/lpc_sniffer_tpm/files/3395820/log1.txt)
[log2.txt](https://github.com/denandz/lpc_sniffer_tpm/files/3395821/log2.txt)

**Comment by denandz** [comment]
Heya, which TPM chip was this run against?

**Comment by Istvan-at** [comment]
It was an ST Microelectronics TPM 1.2 chip on a TSSOP marked "n18fpm0".
STM does not really have a wide spectrum of LPC TMP Chips, so I assume it is the one:
https://www.st.com/content/st_com/en/products/secure-mcus/authentication-secure-iot/trusted-computing-solutions/st33tpm12lpc.html

**Comment by Rolel** [comment]
Hi, same issued here with a STM N18FPVMT found in Dell Optiplex 980.
Do you have any idea or workaround ?

**Comment by denandz** [comment]
There's an issue with the LPC logic when sniffing TPM1.2 chips. Unfortunately I don't have a work around at this time. If you have access to a logic analyser I would suggest trying that method instead? The LPC TPM decoder has been merged into DSView's master.

**Comment by Rolel** [comment]
Thanks for your answer.
I have no logic analyzer but will try to find this.

**Comment by Rolel** [comment]
Also having the issue but this time on a SLB9635B, TPM 1.2 too.

**Comment by Rolel** [comment]
Another info: sniffer is working with a AT97SC3205 (Atmel) TPM using 1.2 protocol.
This is the chip in Dell Optiplex 745.

**Comment by denandz** [comment]
Looks like this issue should be resolved thanks to the work by @Rolel (specifically, commit 2b601c18f892ff607b983ac184c22e63b6396e79). I'm going to close this issue. If there are issues with other specific chips, we can track those in a separate issue.
